In [2]:
import numpy as np

A = np.array(
    [
        [10.0, -1.0, 2.0, 0.0],
        [-1.0, 11.0, -1.0, 3.0],
        [2.0, -1.0, 10.0, -1.0],
        [0.0, 3.0, -1.0, 8.0],
    ]
)

b = np.array([6.0, 25.0, -11.0, 15.0])

print("System of equations:")
for i in range(A.shape[0]):
    equation = ""
    for j in range(A.shape[1]):
        equation += f"{A[i][j]}*{j+1}"
        if j < A.shape[1] - 1:
            equation += " + "
    equation += f" = {b[i]}"
    print(equation)

System of equations:
10.0*1 + -1.0*2 + 2.0*3 + 0.0*4 = 6.0
-1.0*1 + 11.0*2 + -1.0*3 + 3.0*4 = 25.0
2.0*1 + -1.0*2 + 10.0*3 + -1.0*4 = -11.0
0.0*1 + 3.0*2 + -1.0*3 + 8.0*4 = 15.0


In [3]:
def gauss_seidel(A, b):
    TOLERANCE = 1e-8
    ITERATION_LIMIT = 1000

    x = np.zeros_like(b)
    n = len(b)
    
    while ITERATION_LIMIT > 0:
        ITERATION_LIMIT -= 1
        x_old = np.copy(x)
        for i in range(n):
            x[i] = (b[i] - (np.dot(A[i, :i], x[:i]) + np.dot(A[i, i+1:], x_old[i+1:]))) / A[i, i]
        if np.linalg.norm(x - x_old, ord=np.inf) < TOLERANCE:
            break
    return x

solution = gauss_seidel(A, b)
print("Solution using Gauss-Seidel iteration:")
print(solution)

Solution using Gauss-Seidel iteration:
[ 1.  2. -1.  1.]


In [5]:
def jacobi(A, b):
    TOLERANCE = 1e-8
    ITERATION_LIMIT = 1000

    x = np.zeros_like(b)
    n = len(b)
    x_new = np.zeros_like(x)
    for _ in range(ITERATION_LIMIT):
        for i in range(n):
            x_new[i] = (b[i] - np.dot(A[i, :i], x[:i]) - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]
        if np.linalg.norm(x_new - x, ord=np.inf) < TOLERANCE:
            break
        x = np.copy(x_new)
    return x

solution = jacobi(A, b)
print("Solution using Jacobi iteration:")
print(solution)

Solution using Jacobi iteration:
[ 1.  2. -1.  1.]


In [10]:
def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = np.zeros((n, n))
    
    for i in range(n):
        # Upper Triangular Matrix
        for k in range(i, n):
            sum = 0
            for j in range(i):
                sum += L[i][j] * U[j][k]
            U[i][k] = A[i][k] - sum
            U[i][k] = round(U[i][k], 2)
        
        # Lower Triangular Matrix
        for k in range(i, n):
            if i == k:
                L[i][i] = 1
            else:
                sum = 0
                for j in range(i):
                    sum += L[k][j] * U[j][i]
                L[k][i] = (A[k][i] - sum) / U[i][i]
                L[k][i] = round(L[k][i], 2)
    
    return L, U

L, U = lu_decomposition(A)
print(L)
print(U)

[[ 1.    0.    0.    0.  ]
 [-0.1   1.    0.    0.  ]
 [ 0.2  -0.07  1.    0.  ]
 [ 0.    0.28 -0.08  1.  ]]
[[10.   -1.    2.    0.  ]
 [ 0.   10.9  -0.8   3.  ]
 [ 0.    0.    9.54 -0.79]
 [ 0.    0.    0.    7.1 ]]
